
fig,axes = plt.subplots(1, 3, figsize=(40, 20), dpi=300)

psin = get_psin(eq)
psi =   get_psi(eq)
n = get_n(eq)
Te = get_Te(eq)
vol = get_vol(eq)
dvoldp = get_volp(eq)
np.trapezoid(vol,psi)
np.trapezoid(dvoldp,psi)
axes[0].plot(psin, n/1e20)
axes[0].set_xlabel(r"$\psi_n$")
axes[0].set_ylabel(r"Density $[10^{20} \, \mathrm{m}^{-3}]$")
axes[0].set_title("Density profile")
axes[1].plot(psin, Te/1e3)
axes[1].set_xlabel(r"$\psi_n$")
axes[1].set_ylabel(r"Temperature $[\mathrm{keV}]$")
axes[1].set_title("Temperature profile")
axes[2].plot(psin, vol)
axes[2].set_xlabel(r"$\psi_n$")
axes[2].set_ylabel(r"Volume $[\mathrm{m^3}]$")
axes[2].set_title("Volume profile") 
plt.tight_layout()
plt.show()